### ISSUE TITLE
Error:(16, 0) Could not find property 'keyalias' on project ':app'.

### ISSUE THREAD

**Issue by killpigman** [kaichunlin/android-transition#1]

**Comment by kaichunlin** [comment]
You can comment out these scripts in app's build.gradle:

        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

OR pull the latest version, but note that the new version is in beta and is incompatible with older versions.
