### ISSUE TITLE
slidingUpPannel快速滑动事件冲突

### ISSUE THREAD

**Issue by fanyu2013** [kaichunlin/android-transition#2]
slidingUpPannel会截取listview的快速滑动事件，使得listview只能慢速滑动。

**Comment by fanyu2013** [comment]
望作者提供解决方案

**Comment by kaichunlin** [comment]
這issue看起來應該是要提交給[AndroidSlidingUpPanel](https://github.com/umano/AndroidSlidingUpPanel)?

**Comment by fanyu2013** [comment]
AndroidSlidingUpPanel的最新版本已经解决这个问题了，但是我用您的包加transition后不支持。

**Comment by kaichunlin** [comment]
聽起來是更新library用的AndroidSlidingUpPanel版本即可解決，回國後馬上處理，謝謝你的提醒～

**Comment by fanyu2013** [comment]
ok~
